services:

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dvb:/dev/dvb
      - /dev/dri:/dev/dri  # Intel QuickSync hardware acceleration

    group_add:
      - "video"
      - "992"
    privileged: true
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/tom/MediaStack/config/plex:/config
      - /media:/media
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    network_mode: "container:shared-vpn"

    environment:
      - PUID=1001  # Change to your user ID
      - PGID=1001  # Change to your group ID
      - TZ=America/New_York  # Change to your timezone
      - UMASK_SET=022
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - nodeID=MainNode
      - auth=true
    volumes:
      - /home/tom/MediaStack/config/tdarr/server:/app/server
      - /home/tom/MediaStack/config/tdarr/config:/app/configs
      - /home/tom/MediaStack/config/tdarr/logs:/app/logs
      # Media directories - adjust these to match your setup
      - /media/videos/media/movies:/content/movies
      - /media/videos/media/tv:/content/tv
      - /media/videos/media/youtube:/content/youtube
      # Temporary transcoding directory (should be fast storage if possible)
      - /media/videos/media/cache:/content/cache
      - /home/tom/scripts:/shared-scripts:ro
    healthcheck:
      test: ["CMD", "/shared-scripts/vpn_healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri  # Intel QuickSync hardware acceleration
    group_add:
      - "992"


  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:shared-vpn"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York  # Adjust to your timezone
      - WEBUI_PORT=8080
    volumes:
      - /home/tom/MediaStack/config/qbittorrent:/config
      - /home/tom/MediaStack/config/vuetorrent:/vuetorrent
      - /media:/media
      - /home/tom/scripts:/shared-scripts:ro
    healthcheck:
      test: ["CMD", "/shared-scripts/vpn_healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    network_mode: "container:shared-vpn"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/tom/MediaStack/config/prowlarr:/config
      - /home/tom/scripts:/shared-scripts:ro
    healthcheck:
      test: ["CMD", "/shared-scripts/vpn_healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    network_mode: "container:shared-vpn"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/tom/MediaStack/config/sonarr:/config
      - /media:/media
      - /home/tom/scripts:/shared-scripts:ro
    healthcheck:
      test: ["CMD", "/shared-scripts/vpn_healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    network_mode: "container:shared-vpn"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/tom/MediaStack/config/radarr:/config
      - /media:/media
      - /home/tom/scripts:/shared-scripts:ro
    healthcheck:
      test: ["CMD", "/shared-scripts/vpn_healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  pinchflat:
    container_name: pinchflat
    image: ghcr.io/kieraneglin/pinchflat:latest
    network_mode: "container:shared-vpn"
    environment:
      # Set the timezone to your local timezone
      - TZ=America/New_York

    volumes:
      - /home/tom/MediaStack/config/pinchflat:/config
      - /media/videos/media/youtube:/downloads
      - /home/tom/scripts:/shared-scripts:ro
    healthcheck:
      test: ["CMD", "/shared-scripts/vpn_healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: "container:shared-vpn"
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - CAPTCHA_SOLVER=none
      - TEST_URL=https://www.google.com  # Add this to test connectivity
      - BROWSER_TIMEOUT=40000  # Increase timeout
      - PROXY_SERVER=  # Leave empty to use direct connection through VPN
    volumes:
      - /home/tom/scripts:/shared-scripts:ro
    healthcheck:
      test: ["CMD", "/shared-scripts/vpn_healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped


  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    devices:
      # Exposes the GPU device to the container
      - /dev/dri:/dev/dri
    group_add:
      - "video"
      # Add other necessary group IDs here, if any, similar to Plex's 992
      - "992"
    volumes:
      - /home/tom/MediaStack/config/jellyfin/config:/config 
      - /home/tom/MediaStack/config/jellyfin/cache:/cache 
      - /media/videos/media/movies:/data/movies:ro # :ro means Read-Only
      - /media/videos/media/tv:/data/tvshows:ro # :ro means Read-Only
    ports:
      # Main access port for the web interface (Host:Container)
      - 8096:8096 
      # Optional: UDP port for discovery (DLNA)
      - 7359:7359/udp

  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    restart: unless-stopped
    # Use host network mode for direct tuner access and easy Jellyfin communication
    network_mode: host 
    # Map the Digital Video Broadcasting (DVB) device for the OTA tuner
    devices:
      - /dev/dvb:/dev/dvb
    group_add:
      - "video" # Ensures proper permissions for device access
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      
    volumes:
      # Persistent storage for TVHeadend configuration, channel data, EPG cache
      - /home/tom/MediaStack/config/tvheadend:/config 
      # Optional: Add a volume for DVR recordings if you plan to use that feature
      #- /media/videos/media/dvr:/recordings

